import { Metadata } from "next";
import Link from "next/link";
import './global.css';
 
export const metadata:Metadata = {
  title:{
    absolute:'',
	  default:'NextApp',
	  template:''  
  }
  ,
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        style={{
          display:'flex',
          flexDirection:'column',
          alignItems:'center',
          margin:'0',
          padding:'0',
          minHeight:'100vh'
        }}
      >
        <header
          style={{
            backgroundColor:'rebeccapurple',
            padding:'20px',
            width:'100%',
            textAlign:"center",
            position:'relative'
          }}>
            <Link
               href={'/'} 
               style={{
                color:'white',
                position:'absolute',
                top:'6px',
                right:'39px',
                backgroundColor:'black',
                padding:'3px',
                border:'2px solid white',      
                }}>Home page</Link>
          </header>
          {children}
        <footer 
          style={{
            backgroundColor:'blanchedalmond',
            padding:'20px',
            width:'100%',
            textAlign:"center"
          }}>
          </footer>
      </body>
    </html>
  );
}
